name: Python package

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install
    - name: Verify pytest installation
      run: pytest --version
    - name: Clean previous test artifacts
      run: make clean
    - name: Run tests and generate coverage report
      run: make coverage
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml
    - name: Lint code
      run: make lint
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: src/tests
